Repository DOM-C1/Climate-Monitor, pull requests merged in 2024-04, with the labels that each got.

#9 Add issue templates
  .github/ISSUE_TEMPLATE/01-new-feature.md
  .github/ISSUE_TEMPLATE/02-feature-update.md
  .github/ISSUE_TEMPLATE/03-bug-fix.md
  .github/ISSUE_TEMPLATE/04-documentation.md
  .github/ISSUE_TEMPLATE/05-project-setup.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: project setup

#70 Sql schema #69
  .gitignore
  database/enter_database.sh
  database/schema.sql
Labels: project setup

#71 Transform
  ETL_pipeline/load_flood.py
  ETL_pipeline/requirements.txt
  ETL_pipeline/transform.py
  ETL_pipeline/transform_flood.py
  database/enter_database.sh
  database/initialise-database.sh
  database/insert_metadata.py
  database/metadata/counties.txt
  database/metadata/emergencies.txt
  database/metadata/severities.txt
  requirements.txt
Labels: new feature

#89 Emailing alerts
  database/dummy_data.sh
  database/dummy_data.sql
  database/schema.sql
  email_alerts/create_email_messages.py
  email_alerts/email_alert_setup.py
  email_alerts/requirements.txt
  email_alerts/send_email.py
  email_alerts/test_emails.py
  email_alerts/update_alerts.py
Labels: new feature

#92 Delete script
  delete_old/delete.py
  email_alerts/create_email_messages.py
  email_alerts/email_alert_setup.py
  email_alerts/send_email.py
  email_alerts/test_emails.py
  email_alerts/update_alerts.py
Labels: feature update

#87 Fix splitter output
  location_splitter/Dockerfile
  location_splitter/location_splitter.py
  location_splitter/requirements.txt
Labels: bug fix

#96 Email rework
  email_alerts/create_email_messages.py
  email_alerts/email_alert_setup.py
  email_alerts/s.html
  email_alerts/send_email.py
  email_alerts/test_emails.py
  email_alerts/update_alerts.py
Labels: feature update

#100 dockerised delete script #98
  delete_old/Dockerfile
  delete_old/delete.py
  delete_old/requirements.txt
Labels: feature update

#107 Pipeline fixes
  flood_ETL/extract_flood.py
  flood_ETL/load_flood.py
  flood_ETL/transform_flood.py
  location_splitter/location_splitter.py
Labels: bug fix

#103 Async pipeline
  ETL_pipeline/extract.py
  ETL_pipeline/pipeline.py
  ETL_pipeline/requirements.txt
  ETL_pipeline/transform.py
Labels: bug fix

#106 Dockerise emails
  email_alerts/Dockerfile
  email_alerts/s.html
  email_alerts/send_email.py
Labels: feature update

#108 Daily report
  .gitignore
  ERD.png
  README
  README.md
  architecture-diagram.png
  daily_report/Dockerfile
  daily_report/report.py
  daily_report/requirements.txt
  static
  terraform/main.tf
  terraform/website.tf
  website/app.py
  website/templates/newsletter.html
  website/templates/user_not_found.html
  website/utils_db.py
Labels: documentation
