Repository DOM-C1/Climate-Monitor, pull requests merged in 2024-05, with the labels that each got.

#114 Terraform
  database/dummy_data.sh
  database/dummy_data.sql
  email_alerts/create_email_messages.py
  terraform/event_bridge.tf
  terraform/lambdas.tf
Labels: feature update

#117 adding an eventbridge terraform for daily report
  terraform/event_bridge.tf
Labels: feature update

#112 Etl overwrite fix
  ETL_pipeline/load.py
  ETL_pipeline/pipeline.py
Labels: bug fix

#120 updated to check the location table using loc_name instead of long an…
  flood_ETL/load_flood.py
  flood_ETL/transform_flood.py
  website/utils_db.py
Labels: bug fix

#121 updated flood pipeline to no longer record un-recorded locations
  flood_ETL/load_flood.py
  flood_ETL/transform_flood.py
Labels: bug fix

#123 Update schema.sql
  database/schema.sql
Labels: feature update

#122 Bug fix email
  email_alerts/create_email_messages.py
  email_alerts/send_email.py
Labels: bug fix

#124 Terraform installation guide
  ERD.png
  README.md
  architecture-diagram.png
Labels: documentation

#130 finish readme
  README.md
  alert.png
  report.png
Labels: documentation

#129 Dashboard
  ETL_pipeline/transform.py
  dashboard/.streamlit/config.toml
  dashboard/Dockerfile
  dashboard/Home.py
  dashboard/pages/1_About_this_site.py
  dashboard/pages/2_Explore.py
  dashboard/pages/3_Alerts_across_the_UK.py
  dashboard/pages/4_Sign_Up.py
  dashboard/requirements.txt
  database/schema.sql
Labels: new feature

#132 Dashboard edits - mostly satisfying pylint
  dashboard/Home.py
  dashboard/pages/1_About_this_site.py
  dashboard/pages/2_Explore.py
  dashboard/pages/3_Alerts_across_the_UK.py
  dashboard/pages/4_Sign_Up.py
Labels: documentation, feature update
